---
version: "3.8"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/
      DATABASE_HOST: postgres
    #ports:
      #- "3000:3000"
      #- "9229:9229"
    command: sh ./bin/entrypoint_dev.sh
    volumes:
      - .:/var/app:delegated